-- 회원 테이블
DROP TABLE MEMBER 
	CASCADE CONSTRAINTS;

CREATE TABLE MEMBER (
	EMAIL VARCHAR2(100) PRIMARY KEY, /* 이메일 */
	MEMBER_NAME VARCHAR2(30) NOT NULL, /* 이름 */
	PASSWORD VARCHAR2(80) NOT NULL, /* 비밀번호 */
	MAIN_ADDRESS VARCHAR2(100) NOT NULL, /* 기본주소 */
	SUB_ADDRESS VARCHAR2(100) NOT NULL, /* 상세주소 */
	ZIPCODE NUMBER(5) NOT NULL, /* 우편번호 */
	MEMBER_IMAGE VARCHAR2(100), /* 이미지 */
	PHONENUM VARCHAR2(20) NOT NULL, /* 연락처 */
	MEMBER_ENABLE NUMBER(1) DEFAULT 1 NOT NULL
);

insert into member values('suil@naver.com','김동수','1111','서울','마포',12345,'image1','010-7123-1223',0);
insert into member values('suil1@naver.com','김상민','1121','서울','마포',12345,'image1','010-7123-1223',0);
insert into member values('suil2@naver.com','김장미','1131','서울','마포',12345,'image1','010-7123-1223',0);
insert into member values('suil3@naver.com','김수미','1141','서울','마포',12345,'image1','010-7123-1223',0);

select * from member

-- 권한 테이블
DROP TABLE AUTHORITY 
	CASCADE CONSTRAINTS;

CREATE TABLE AUTHORITY (
	EMAIL VARCHAR2(100) NOT NULL, /* 이메일 */
	AUTHORITY VARCHAR2(20) NOT NULL, /* 권한 */
	CONSTRAINT PK_AUTHORITY PRIMARY KEY(EMAIL,AUTHORITY),
	CONSTRAINT FK_AUTHORITY_MEMBER FOREIGN KEY(EMAIL) REFERENCES MEMBER ON DELETE CASCADE
);

insert into AUTHORITY values('suil@naver.com','ROLE_USER');
insert into AUTHORITY values('suil@naver.com','ROLE_ADMIN');
insert into AUTHORITY values('suil@naver.com','ROLE_SITTER');
insert into AUTHORITY values('suil@naver.com','ROLE_ADMIN');

select * from AUTHORITY

--코드 테이블
DROP TABLE CODE 
	CASCADE CONSTRAINTS;

CREATE TABLE CODE (
	CODE VARCHAR2(20) PRIMARY KEY, /* 코드 */
	CODE_NAME VARCHAR2(100) NOT NULL, /* 코드이름 */
	CATEGORY VARCHAR2(100) NOT NULL /* 카테고리 */
);

insert into code values('1','반려동물 경험 유무','시터');
insert into code values('2','펫트너 집에서 보살필 수 있어요','시터');
insert into code values('3','고객의 집에서 보살필 수 있어요','시터');
insert into code values('4','투약가능','시터');
insert into code values('5','노령견 케어 가능','시터');
insert into code values('6','퍼피 케어 가능','시터');
insert into code values('7','환자 모니터링 가능','시터');
INSERT INTO CODE VALUES('8','배변활동','강아지');
INSERT INTO CODE VALUES('9','심장사상충','강아지');
INSERT INTO CODE VALUES('10','당뇨','강아지');

select * from code

--강아지정보 테이블
DROP TABLE DOGINFO 
	CASCADE CONSTRAINTS;

/* 강아지정보 */
CREATE TABLE DOGINFO (
	DOG_ID NUMBER(5) NOT NULL, /* 강아지ID */
	CODE VARCHAR2(20) NOT NULL, /* 코드 */
	CONSTRAINT FK_DOGINFO_DOG FOREIGN KEY(DOG_ID) REFERENCES DOG ON DELETE CASCADE,
	CONSTRAINT FK_DOGINFO_CODE FOREIGN KEY(CODE) REFERENCES CODE ON DELETE CASCADE
);

INSERT INTO DOGINFO VALUES('1','8');
INSERT INTO DOGINFO VALUES('1','9');
INSERT INTO DOGINFO VALUES('1','10');
INSERT INTO DOGINFO VALUES('5','1');


-- 강아지 테이블
DROP TABLE DOG 
	CASCADE CONSTRAINTS;

CREATE TABLE DOG (
	DOG_ID NUMBER(5) PRIMARY KEY, /* 강아지ID */
	DOG_NAME VARCHAR2(30) NOT NULL, /* 이름 */
	SPECIES VARCHAR2(50) NOT NULL, /* 종 */
	GENDER VARCHAR2(50) NOT NULL, /* 성별 */
	WEIGHT NUMBER(3, 1) NOT NULL, /* 몸무게 */
	BIRTH DATE NOT NULL, /* 생년월일 */
	CODE VARCHAR2(20) , /* 코드 */
	EMAIL VARCHAR2(100), /* 이메일 */
	CONSTRAINT FK_DOG_CODE FOREIGN KEY(CODE) REFERENCES CODE ON DELETE CASCADE,
	CONSTRAINT FK_DOG_MEMBER FOREIGN KEY(EMAIL) REFERENCES MEMBER ON DELETE CASCADE
);

INSERT INTO DOG VALUES('1','미륵','비숑','암컷',3.5,'20100608','1','suil@naver.com');
INSERT INTO DOG VALUES('2','미륵1','슈바이처','암컷',4.5,'20100608','2','suil@naver.com');
INSERT INTO DOG VALUES('3','미륵2','진돗개','수컷',5.5,'20100608','3','suil@naver.com');
INSERT INTO DOG VALUES('4','미륵3','삽살개','투컷',6.5,'20100608','4','suil@naver.com');
INSERT INTO DOG VALUES(5,'미륵3','삽살개','투컷',6.5,'20100608','4','suil@naver.com');

SELECT C.CODE_NAME, D.DOG_NAME FROM DOG D , CODE C, DOGINFO I WHERE D.DOG_ID = I.DOG_ID AND I.CODE = C.CODE 

-- 강아지 이미지 테이블 
DROP TABLE DOG_IMAGE 
	CASCADE CONSTRAINTS		
		
CREATE TABLE DOG_IMAGE (
	DOG_IMAGE VARCHAR2(100) NOT NULL, /* 이미지이름(경로) */
	DOG_ID NUMBER(5), /* 강아지ID */
	CONSTRAINT FK_DOG_IMAGE_DOG FOREIGN KEY(DOG_ID) REFERENCES DOG ON DELETE CASCADE
);

INSERT INTO DOG_IMAGE VALUES('SDFLKJSDFL','')

-- 시터 테이블
DROP TABLE SITTER 
	CASCADE CONSTRAINTS;

CREATE TABLE SITTER (
	EMAIL VARCHAR2(100) NOT NULL, /* 이메일 */
	SCHOOL VARCHAR2(50) NOT NULL, /* 학교이름 */
	CERTIFICATION VARCHAR2(100) NOT NULL, /* 증명서/면허증 */
	SERVICE_ADDRESS CLOB NOT NULL, /* 서비스가능지역 */
	SITTER_RATE NUMBER(2, 1), /* 평점 */
	CONSTRAINT PK_SITTER PRIMARY KEY(EMAIL),
	CONSTRAINT FK_SITTER_MEMBER FOREIGN KEY(EMAIL) REFERENCES MEMBER ON DELETE CASCADE
);

-- 스킬 테이블
DROP TABLE SKILL 
	CASCADE CONSTRAINTS;

/* 스킬 */
CREATE TABLE SKILL (
	EMAIL VARCHAR2(100) NOT NULL, /* 이메일 */
	CODE_SKILL VARCHAR2(20) NOT NULL, /* 코드 */
	CONSTRAINT FK_SKILL_MEMBER FOREIGN KEY(EMAIL) REFERENCES SITTER ON DELETE CASCADE,
	CONSTRAINT FK_SKILL_CODE FOREIGN KEY(CODE_SKILL) REFERENCES CODE ON DELETE CASCADE
);

-- 리뷰 테이블
DROP TABLE REVIEW 
	CASCADE CONSTRAINTS;

/* 리뷰 */
CREATE TABLE REVIEW (
	REVIEW_ID NUMBER(10) PRIMARY KEY, /* 리뷰ID */
	REVIEW_RATE NUMBER(1), /* 별점 */
	REVIEW_CONTENTS CLOB NOT NULL, /* 내용 */
	EMAIL VARCHAR2(100) , /* 견주_이메일 */
	EMAIL2 VARCHAR2(100), /* 시터_이메일 */
	CONSTRAINT FK_REVIEW_MEMBER FOREIGN KEY(EMAIL) REFERENCES MEMBER ON DELETE CASCADE,
	CONSTRAINT FK_REVIEWL_SITTER FOREIGN KEY(EMAIL2) REFERENCES SITTER ON DELETE CASCADE
);

-- 예약 테이블
DROP TABLE RESERVATION 
	CASCADE CONSTRAINTS;

/* 예약 */
CREATE TABLE RESERVATION (
	RES_ID NUMBER(10) PRIMARY KEY, /* 예약ID */
	RES_TYPE NUMBER(1) NOT NULL, /* 의뢰종류 */
	RES_SDATE DATE NOT NULL, /* 시작날짜 */
	RES_EDATE DATE NOT NULL, /* 종료날짜 */
	RES_CONTENTS CLOB NOT NULL, /* 의뢰내용 */
	EMAIL VARCHAR2(100), /* 견주_이메일 */
	EMAIL2 VARCHAR2(100), /* 시터_이메일 */
	CONSTRAINT FK_RESERVATION_MEMBER FOREIGN KEY(EMAIL) REFERENCES MEMBER ON DELETE CASCADE,
	CONSTRAINT FK_RESERVATION_SITTER FOREIGN KEY(EMAIL2) REFERENCES SITTER ON DELETE CASCADE
);

/* 매출 */
CREATE TABLE SALES (
	RES_ID NUMBER(10) NOT NULL, /* 예약ID */
	TOTAL NUMBER(15) NOT NULL, /* 총액 */
	PAY NUMBER(15), /* 시터 수입 */
	COMMISSION NUMBER(15) NOT NULL, /* 수수료 */
	SALES_DATE DATE NOT NULL, /* 결제날짜 */
	CONSTRAINT FK_SALES_RESERVATION FOREIGN KEY(RES_ID) REFERENCES RESERVATION ON DELETE CASCADE
);

-- 서비스 요구사항 테이블
DROP TABLE DEMAND 
	CASCADE CONSTRAINTS;

/* 서비스 요구사항 */
CREATE TABLE DEMAND (
	RES_ID NUMBER(10) NOT NULL, /* 예약ID */
	CODE VARCHAR2(20) NOT NULL, /* 코드 */
	CONSTRAINT FK_DEMAND_RESERVATION FOREIGN KEY(RES_ID) REFERENCES RESERVATION ON DELETE CASCADE,
	CONSTRAINT FK_DEMAND_CODE FOREIGN KEY(CODE) REFERENCES CODE ON DELETE CASCADE
);

-- 돌봄일지 테이블
DROP TABLE CARE 
	CASCADE CONSTRAINTS;

/* 돌봄일지 */
CREATE TABLE CARE (
	CARE_ID NUMBER(10) PRIMARY KEY, /* 돌봄일지ID */
	CARE_CONTENTS CLOB NOT NULL, /* 내용 */
	RES_ID NUMBER(10) NOT NULL, /* 예약ID */
	CARE_DATE DATE NOT NULL, /* 작성일 */
	CONSTRAINT FK_CARE_RESERVATION FOREIGN KEY(RES_ID) REFERENCES RESERVATION ON DELETE CASCADE
);

-- 돌봄일지 이미지 테이블
DROP TABLE CARE_IMAGE 
	CASCADE CONSTRAINTS;

/* 돌봄일지 이미지 */
CREATE TABLE CARE_IMAGE (
	CARE_IMAGE VARCHAR2(30) NOT NULL, /* 이미지경로 */
	CARE_ID NUMBER(10) NOT NULL, /* 돌봄일지ID */
	CONSTRAINT FK_CARE_IMAGE_CARE FOREIGN KEY(CARE_ID) REFERENCES CARE ON DELETE CASCADE
);
		
select * from RESERVATION
